### ISSUE TITLE
Example to open an android app

### ISSUE THREAD

**Issue by emiludev** [enzoferey/react-open-app#11]
Hi, I'm trying to figure out how to use your library to open an android application from my react app.
I just asking for an example to achieve this action.
...
<OpenApp
      href="https://mycoolappwebsite.com"
      android="whatever deep link you need on Android"
      ios="whatever deep link you need on iOS"
    >
      My app
    </OpenApp>
...
Inside the documentation you put this line of code, but for the record, I'm not an Android Developer, so I wonder, what kind of string is spected to put in the android line.

Cheers.

**Comment by enzoferey** [comment]
Hi @emiludev !

You probably misunderstood the docs. From the [usage](https://github.com/enzoferey/react-open-app#usage) section that you are looking at: 

```jsx
<div className="App">
    <h1>Hello World</h1>
    <OpenApp
      href="https://mycoolappwebsite.com"
      android="whatever deep link you need on Android"
      ios="whatever deep link you need on iOS"
    >
      My app
    </OpenApp>
</div>
```

Here, "My app" is just the label that will be displayed as an anchor when rendering the component in your view. You could write "Click here to open the app" or use any kind of other html tag if you want a different visual for the link. Then, you should use the `android` property to set the deeplink that will open the android application you want to target.

Let me know if you have any other question.

**Comment by emiludev** [comment]
Thank you very much @enzoferey , sorry I would like to be clearer, could you share an example of a deeplink to open an android application from the android property, that would be great.

**Comment by enzoferey** [comment]
Hey @emiludev, it depends on the app you want to open. For example, if you want to open Twitter app the string you should put in the `android` property should start like `twitter://` followed by any path you want to deeplink. If you want to open your own native app, you should look at how to setup deeplinks for your app first.

**Comment by emiludev** [comment]
I really appreciate that you helped me understand this.
Now it is clear to me. Thanks. 👍
